"""Generate channel catalog TypeScript from openclaw extension metadata.

Scans openclaw/extensions/*/openclaw.plugin.json for channel plugins,
reads metadata from package.json (openclaw.channel) and falls back to
src/channels/registry.ts (CHAT_CHANNEL_META) for built-in channels.

Output: web/src/generated/channel-catalog.ts
"""

import json
import re
from pathlib import Path
from common import get_logger, get_project_root


# Built-in channel order from openclaw/src/channels/ids.ts
BUILTIN_ORDER = [
    'telegram', 'whatsapp', 'discord', 'irc',
    'googlechat', 'slack', 'signal', 'imessage', 'line',
]


def find_openclaw_root():
    """Locate the openclaw project relative to ocbot."""
    return get_project_root().parent / 'openclaw'


def scan_channel_extensions(openclaw_root):
    """Scan extensions for channel plugins. Returns {channel_id: extension_dir}."""
    extensions_dir = openclaw_root / 'extensions'
    if not extensions_dir.is_dir():
        return {}

    channels = {}
    for ext_dir in sorted(extensions_dir.iterdir()):
        manifest_path = ext_dir / 'openclaw.plugin.json'
        if not manifest_path.is_file():
            continue
        try:
            manifest = json.loads(manifest_path.read_text())
        except (json.JSONDecodeError, OSError):
            continue

        channel_ids = manifest.get('channels', [])
        for cid in channel_ids:
            if cid and isinstance(cid, str):
                channels[cid] = ext_dir
    return channels


def read_package_channel_meta(ext_dir):
    """Read openclaw.channel metadata from extension's package.json."""
    pkg_path = ext_dir / 'package.json'
    if not pkg_path.is_file():
        return {}
    try:
        pkg = json.loads(pkg_path.read_text())
    except (json.JSONDecodeError, OSError):
        return {}
    return pkg.get('openclaw', {}).get('channel', {})


def parse_registry_meta(openclaw_root):
    """Parse CHAT_CHANNEL_META from src/channels/registry.ts.

    Returns {channel_id: {label, detailLabel, blurb}} extracted via regex.
    This is a best-effort parser for the TypeScript object literal.
    """
    registry_path = openclaw_root / 'src' / 'channels' / 'registry.ts'
    if not registry_path.is_file():
        return {}

    content = registry_path.read_text()

    # Find the CHAT_CHANNEL_META block
    match = re.search(
        r'const\s+CHAT_CHANNEL_META[^=]*=\s*\{(.+?)\n\};',
        content, re.DOTALL
    )
    if not match:
        return {}

    block = match.group(1)
    result = {}

    # Split into per-channel blocks: "  channelId: { ... },"
    channel_blocks = re.findall(
        r'(\w+)\s*:\s*\{([^}]+)\}', block
    )

    for cid, body in channel_blocks:
        meta = {}
        for key in ('label', 'detailLabel', 'selectionLabel', 'blurb'):
            m = re.search(rf'{key}\s*:\s*["\']([^"\']+)["\']', body)
            if m:
                meta[key] = m.group(1)
        if meta:
            result[cid] = meta

    return result


def build_catalog(openclaw_root):
    """Build the channel catalog entries."""
    channel_extensions = scan_channel_extensions(openclaw_root)
    registry_meta = parse_registry_meta(openclaw_root)

    entries = []
    for cid, ext_dir in channel_extensions.items():
        pkg_meta = read_package_channel_meta(ext_dir)

        # Merge: package.json wins, registry.ts fills gaps
        reg = registry_meta.get(cid, {})

        label = pkg_meta.get('label') or reg.get('label') or cid.replace('-', ' ').title()
        detail_label = pkg_meta.get('detailLabel') or reg.get('detailLabel') or label
        blurb = pkg_meta.get('blurb') or reg.get('blurb') or ''

        # Order: built-in channels use their position in BUILTIN_ORDER,
        # extension channels get order from metadata or sort to the end
        if cid in BUILTIN_ORDER:
            order = BUILTIN_ORDER.index(cid)
        else:
            order = pkg_meta.get('order', 100 + len(entries))

        entries.append({
            'id': cid,
            'label': label,
            'detailLabel': detail_label,
            'blurb': blurb,
            'order': order,
        })

    entries.sort(key=lambda e: (e['order'], e['label']))
    return entries


def escape_ts_string(s):
    """Escape a string for use in a TypeScript string literal."""
    return s.replace('\\', '\\\\').replace("'", "\\'")


def write_catalog_ts(entries, output_path):
    """Write the TypeScript catalog file."""
    lines = [
        '// Auto-generated by scripts/gen_channel_catalog.py — do not edit manually.',
        '',
        'export interface ChannelCatalogEntry {',
        '  id: string',
        '  label: string',
        '  detailLabel: string',
        '  blurb: string',
        '  order: number',
        '}',
        '',
        'export const CHANNEL_CATALOG: ChannelCatalogEntry[] = [',
    ]

    for entry in entries:
        lines.append(
            f"  {{ id: '{escape_ts_string(entry['id'])}', "
            f"label: '{escape_ts_string(entry['label'])}', "
            f"detailLabel: '{escape_ts_string(entry['detailLabel'])}', "
            f"blurb: '{escape_ts_string(entry['blurb'])}', "
            f"order: {entry['order']} }},"
        )

    lines.append(']')
    lines.append('')

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text('\n'.join(lines))


def generate(logger=None):
    """Main entry point."""
    if logger is None:
        logger = get_logger()

    openclaw_root = find_openclaw_root()
    if not openclaw_root.is_dir():
        logger.error(f'OpenClaw project not found at {openclaw_root}')
        return False

    entries = build_catalog(openclaw_root)
    output_path = get_project_root() / 'web' / 'src' / 'generated' / 'channel-catalog.ts'
    write_catalog_ts(entries, output_path)

    logger.info(f'Generated channel catalog: {len(entries)} channels → {output_path}')
    return True


if __name__ == '__main__':
    generate()
